service: visual-embedding-api

frameworkVersion: '2'


provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  timeout: 100
  ecr:
    images: # Definitions of images that later can be referenced by key in `function.image`
      baseimage:
        uri: 983570756921.dkr.ecr.us-east-1.amazonaws.com/dog-finder-search@${env:DIGGEST}


functions:
  hello:
    image:
      name: baseimage
    events:
      - http:
          path: /
          method: get

  predict:
    image:
      name: baseimage
      command:
        - app.predict
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /predict
          method: post

  predict_save:
    image:
      name: baseimage
      command:
        - app.predict_save
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /predict-save
          method: post

  search:
    image:
      name: baseimage
      command:
        - app.search
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /search
          method: post
  random:
    image:
      name: baseimage
      command:
        - app.random
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /random
          method: post
  es:
    image:
      name: baseimage
      command:
        - app.es
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /es
          method: post

plugins:
  - serverless-offline