service: visual-embedding-api

frameworkVersion: '2'


provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  timeout: 100
  memorySize: 3008
  environment:
    LAMBDA_ENV: ${self:provider.stage}
  ecr:
    images: 
      baseimage:
        uri: 983570756921.dkr.ecr.us-east-1.amazonaws.com/dog-finder-search-${self:provider.stage}:latest
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: "*"
        - Effect: 'Allow'
          Action:
            - "sts:AssumeRole"
          Resource: "arn:aws:iam::111465656160:role/query-elasticsearch"

functions:
  hello:
    warmup:
      default:
        enabled: false
    image:
      name: baseimage
    events:
      - http:
          path: /
          method: get

  predict:
    warmup:
      default:
        enabled: true
    image:
      name: baseimage
      command:
        - app.predict
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /predict
          method: post

  predict_save:
    warmup:
      default:
        enabled: true
    image:
      name: baseimage
      command:
        - app.predict_save
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /predict-save
          method: post

  search:
    warmup:
      default:
        enabled: true
    image:
      name: baseimage
      command:
        - app.search
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /search
          method: post
  random:
    warmup:
      default:
        enabled: true
    image:
      name: baseimage
      command:
        - app.random
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /random
          method: post
  es:
    warmup:
      default:
        enabled: true
    image:
      name: baseimage
      command:
        - app.es_route
      entryPoint:
        - '/lambda-entrypoint.sh'
    events:
      - http:
          path: /es
          method: post

  update-vectors:
    warmup:
      default:
        enabled: false
    image:
      name: baseimage
      command:
        - app.update_vectors
      entryPoint:
        - '/lambda-entrypoint.sh'
    timeout: 900

plugins:
  - serverless-plugin-warmup
  - serverless-offline

custom:
  warmup:
    default:
      enabled: true
      prewarm: true
      timeout: 100